# Generated by Django 4.1.7 on 2023-02-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_anonymous_alter_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='anonymous',
            field=models.BooleanField(default=True),
        ),
    ]
